import sanitizeHtml from 'sanitize-html';

const SVG_TAGS = [
  'a',
  'circle',
  'clipPath',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'g',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'stop',
  'style',
  'svg',
  'symbol',
  'text',
  'textPath',
  'title',
  'tspan',
  'use',
];

const SVG_ATTRIBUTES = [
  'alignment-baseline',
  'aria-*',
  'azimuth',
  'baseFrequency',
  'class',
  'clip-path',
  'clip-rule',
  'clipPathUnits',
  'color-interpolation-filters',
  'cx',
  'cy',
  'd',
  'dominant-baseline',
  'dx',
  'dy',
  'elevation',
  'fill',
  'fill-opacity',
  'fill-rule',
  'filter',
  'filterUnits',
  'flood-color',
  'flood-opacity',
  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'fx',
  'fy',
  'gradientTransform',
  'gradientUnits',
  'height',
  'href',
  'id',
  'in',
  'in2',
  'k1',
  'k2',
  'k3',
  'k4',
  'lengthAdjust',
  'limitingConeAngle',
  'marker-end',
  'marker-mid',
  'marker-start',
  'markerHeight',
  'markerUnits',
  'markerWidth',
  'mask',
  'maskUnits',
  'method',
  'numOctaves',
  'offset',
  'opacity',
  'operator',
  'orient',
  'paint-order',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'points',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAspectRatio',
  'r',
  'refX',
  'refY',
  'result',
  'role',
  'rx',
  'ry',
  'scale',
  'seed',
  'shape-rendering',
  'spacing',
  'specularConstant',
  'specularExponent',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  'stitchTiles',
  'stop-color',
  'stop-opacity',
  'stroke',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-opacity',
  'stroke-width',
  'style',
  'surfaceScale',
  'tabindex',
  'text-anchor',
  'textLength',
  'transform',
  'type',
  'values',
  'vector-effect',
  'version',
  'viewBox',
  'width',
  'x',
  'x1',
  'x2',
  'xChannelSelector',
  'xlink:href',
  'xmlns',
  'xmlns:xlink',
  'y',
  'y1',
  'y2',
  'yChannelSelector',
];

export function sanitizeSvg(svg: string) {
  return sanitizeHtml(svg, {
    allowedTags: SVG_TAGS,
    allowedAttributes: { '*': SVG_ATTRIBUTES },
    allowedSchemes: ['http', 'https', 'data'],
    allowProtocolRelative: false,
    parser: {
      lowerCaseAttributeNames: false,
      lowerCaseTags: false,
    },
  });
}

export function sanitizeText(text: string) {
  return sanitizeHtml(text, {
    allowedTags: [],
    allowedAttributes: {},
  });
}
